---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  roles_path: test/fixtures/roles

verifier:
  name: inspec

platforms:
- name: ubuntu-12.04
- name: ubuntu-14.04
- name: ubuntu-16.04
- name: centos-5.11
- name: centos-6.8
- name: centos-7.2
- name: fedora-21
- name: fedora-22
- name: fedora-23
- name: fedora-24
- name: debian-7.11
- name: debian-8.5

suites:
  - name: default
    run_list:
      - role[salt_master]
      - role[salt_minion]
  - name: version-pin
    run_list:
      - role[salt_master]
      - role[salt_minion]
    attributes:
      salt:
        version: 2016.3.0-1.el7
    includes:
      - centos-7.2
  - name: salt-api
    data_bags_path: "test/integration/default/data_bags"
    encrypted_data_bag_secret_key_path: "test/integration/default/encrypted_data_bag_secret"
    run_list:
      - role[salt_master]
      - role[salt_minion]
    attributes:
      salt:
        key_accept_method: api_key_accept
        master:
          api:
            enable: true
            user:
              enable: true
